// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApi;

#nullable disable

namespace ToDoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20251103112201_AddCategoryToTodo")]
    partial class AddCategoryToTodo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoApi.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Blue",
                            Description = "Learning-related tasks",
                            Name = "Study"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Red",
                            Description = "Work-related tasks",
                            Name = "Work"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Green",
                            Description = "other things",
                            Name = "other"
                        });
                });

            modelBuilder.Entity("ToDoApi.Entity.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            IsComplete = false,
                            Title = "1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsComplete = false,
                            Title = "Learn EF Core"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            IsComplete = true,
                            Title = "Build API"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            IsComplete = false,
                            Title = "4"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            IsComplete = false,
                            Title = "8"
                        });
                });

            modelBuilder.Entity("ToDoApi.Entity.TodoItem", b =>
                {
                    b.HasOne("ToDoApi.Entity.Category", "Category")
                        .WithMany("Todos")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ToDoApi.Entity.Category", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
